# Generated by Django 5.0.1 on 2024-02-09 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystalSoft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_expense', models.BooleanField()),
                ('add_edit_income', models.BooleanField()),
                ('add_new_item', models.BooleanField()),
                ('add_purchase', models.BooleanField()),
                ('view_dashboard', models.BooleanField()),
                ('view_sale_invoices', models.BooleanField()),
                ('view_reports', models.BooleanField()),
                ('view_stock', models.BooleanField()),
                ('view_bill_profit', models.BooleanField()),
                ('open_new_day', models.BooleanField()),
                ('close_day', models.BooleanField()),
                ('attendence_of_employee', models.BooleanField()),
                ('day_summary', models.BooleanField()),
                ('change_sale_price', models.BooleanField()),
                ('change_price', models.BooleanField()),
                ('edit_invoices', models.BooleanField()),
                ('discount_in_sale_price', models.BooleanField()),
                ('make_receipt_voucher', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
